### ISSUE TITLE
Question about Trackr

### ISSUE THREAD

**Issue by pewh** [GO-HACKATHON/go-track#28]
Previously, I would like to congratulate on your Go-Hackathon victory :tada: 

After I learn your README and pitching deck, I'm so curious more about Trackr or sort of it that the price is as low as $1 when purchased in mass scale. Would you mind to share the link or info about cheap tracker device (I assume the price is $1 when purchased in mass scale) that support with Go-Track, has Crowd Locate feature (like TrackR does), and has battery last for 1 year? AFAIK, [currently](https://store.thetrackr.com/bravo/checkout/?lang=ttp://thetrackr_com/bravo#step1) TrackR cheapest price is $12 (purchased in mass scale).

Regards :beers:

**Comment by azaky** [comment]
@pewh Thanks for that, we really appreciate it. Thank you as well for having interest in our project.

One example would be https://www.alibaba.com/product-detail/Mobile-Phone-Application-bluetooth-beacon-and_1970164099.html?spm=a2700.7724838.0.0.DYpLXu&s=p. They claim to have 50-90 meters range and 1-2 years battery life, but we didn't actually contact them for we do not plan to mass-produce it in the near future.

TrackR *sells* it for $12. We would never know how much does it take to build each of them. Moreover, it has additional feature such as Item Ringer (at least it must have mini speaker inside). The $1 price is only for the plain beacon + battery, while for production we have to think about packaging etc. But knowing TrackR sells it for $12, we now know that the production cost is (way) lower than that.
